#pragma once

using namespace ATL;

template <class T>
class CProxy_IImageOleEvents : public IConnectionPointImpl<T, &__uuidof(_IImageOleEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
